

services:
  sensor-service:
    build: ./sensor-service/sensor-service
    container_name: sensor-service
    ports:
      - "8080:8080"
    depends_on:
      - collector-service

  collector-service:
    build: ./collector-service/collector-service
    container_name: collector-service
    ports:
      - "8081:8081"
    depends_on:
      - storage-service
      - alert-service

  storage-service:
    build: ./storage-service/storage-service
    container_name: storage-service
    ports:
      - "8082:8082"
   

  alert-service:
    build: ./alert-service/alert-service
    container_name: alert-service
    ports:
      - "8083:8083"

  frontend-service:
    build: ./frontend-service/frontend-service
    container_name: frontend-service
    ports:
      - "8084:8084"
    depends_on:
      - collector-service
      - alert-service




