

services:
  sensor-service:
    build: ./sensor-service
    ports:
      - "8080:8080"
    depends_on:
      - collector-service

  collector-service:
    build: ./collector-service
    ports:
      - "8081:8081"
    depends_on:
      - storage-service
      - alert-service

  storage-service:
    build: ./storage-service
    ports:
      - "8082:8082"
    depends_on:
      - db

  alert-service:
    build: ./alert-service
    ports:
      - "8083:8083"

  frontend-service:
    build: ./frontend-service
    ports:
      - "8084:8084"
    depends_on:
      - collector-service
      - alert-service

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: clima
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
