server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://db:5432/clima
    username: admin
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "format_sql": true
  application:
    name: storage-service
